import { apiClient } from '@/lib/api-client';
import {
  AnalyticsTimeframe,
  DashboardSummaryData,
  DeterministicInsight,
  DailyTimelineEvent,
} from '@/types/analytics.types';

export const analyticsService = {
  /**
   * Get complete dashboard summary aggregates (KPIs, Gauges, 4 Chart Tabs, Heatmap, PRs, Last Session)
   */
  getDashboardSummary: async (
    timeframe: AnalyticsTimeframe = '7D',
  ): Promise<DashboardSummaryData> => {
    const res = await apiClient.get<any>(`/analytics/dashboard?timeframe=${timeframe}`);
    const data = res?.data?.data !== undefined ? res.data.data : res?.data !== undefined ? res.data : res;
    return data;
  },

  /**
   * Get deterministic insights generated by rule engine
   */
  getInsights: async (): Promise<DeterministicInsight[]> => {
    const res = await apiClient.get<any>('/analytics/insights');
    const data = res?.data?.data !== undefined ? res.data.data : res?.data !== undefined ? res.data : res;
    return Array.isArray(data) ? data : [];
  },

  /**
   * Get today's daily activity timeline
   */
  getDailyTimeline: async (date?: string): Promise<DailyTimelineEvent[]> => {
    const qs = date ? `?date=${encodeURIComponent(date)}` : '';
    const res = await apiClient.get<any>(`/analytics/timeline${qs}`);
    const data = res?.data?.data !== undefined ? res.data.data : res?.data !== undefined ? res.data : res;
    return Array.isArray(data) ? data : [];
  },
};
